version: 0.2

env:
  variables:
    REGION: ap-south-1
    REPO: brain-tasks
    CLUSTER: brain-tasks

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Getting AWS account ID..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:$IMAGE_TAG"
      - echo "Checking if ECR repository exists..."
      - aws ecr describe-repositories --repository-names $REPO --region $REGION || aws ecr create-repository --repository-name $REPO --region $REGION

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO:$IMAGE_TAG .
      - docker tag $REPO:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $IMAGE_URI
      - echo "Rendering Kubernetes manifests..."
      - mkdir -p artifact/k8s
      - sed "s#{{IMAGE_URI}}#$IMAGE_URI#g" k8s/deployment.yaml > artifact/k8s/deployment.yaml
      - cp k8s/service.yaml artifact/k8s/service.yaml
      - echo "Build & push completed successfully on `date`"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - artifact/**/*
  discard-paths: no
