apiVersion: v1
kind: Namespace
metadata:
  name: brain
---
apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-svc
  namespace: brain
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # create NLB
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks
  ports:
    - name: http
      port: 80
      targetPort: 80
